# Generated by Django 5.1 on 2026-06-16 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beroep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=120, verbose_name='Beroep')),
                ('premie_vanaf', models.CharField(blank=True, max_length=20, verbose_name='Premie vanaf')),
                ('omschrijving', models.CharField(blank=True, max_length=255, verbose_name='Omschrijving')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('active', models.BooleanField(default=True, verbose_name='Actief')),
            ],
            options={
                'verbose_name': 'Beroep',
                'verbose_name_plural': 'Beroepen',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogArtikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('categorie', models.CharField(blank=True, max_length=80, verbose_name='Categorie')),
                ('leestijd', models.CharField(blank=True, help_text="bijv. '5 min'", max_length=20, verbose_name='Leestijd')),
                ('datum', models.CharField(blank=True, max_length=40, verbose_name='Datum (weergave)')),
                ('excerpt', models.TextField(blank=True, verbose_name='Samenvatting')),
                ('image_url', models.URLField(blank=True, verbose_name='Afbeelding-URL')),
                ('featured', models.BooleanField(default=False, verbose_name='Uitgelicht')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('active', models.BooleanField(default=True, verbose_name='Actief')),
            ],
            options={
                'verbose_name': 'Blogartikel',
                'verbose_name_plural': 'Blogartikelen',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Dekkingstier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='WA, WA+, Allrisk', max_length=20, verbose_name='Code')),
                ('naam', models.CharField(max_length=120, verbose_name='Naam')),
                ('prijs', models.CharField(help_text='Alleen het getal, bijv. 34', max_length=20, verbose_name='Prijs vanaf (p/mnd)')),
                ('omschrijving', models.CharField(blank=True, max_length=255, verbose_name='Korte omschrijving')),
                ('highlight', models.BooleanField(default=False, verbose_name='Uitgelicht (meest gekozen)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
            ],
            options={
                'verbose_name': 'Dekkingstier',
                'verbose_name_plural': 'Dekkingstiers',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Naam')),
                ('role', models.CharField(max_length=160, verbose_name='Functie')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('tags', models.CharField(blank=True, help_text="Komma-gescheiden, bijv. 'Wft Schade zakelijk, Wft Basis'.", max_length=255, verbose_name="Diploma's / tags")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('active', models.BooleanField(default=True, verbose_name='Actief')),
            ],
            options={
                'verbose_name': 'Expert',
                'verbose_name_plural': 'Experts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.SlugField(default='home', max_length=60, verbose_name='Pagina')),
                ('question', models.CharField(max_length=255, verbose_name='Vraag')),
                ('answer', models.TextField(verbose_name='Antwoord')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('active', models.BooleanField(default=True, verbose_name='Actief')),
            ],
            options={
                'verbose_name': 'FAQ-item',
                'verbose_name_plural': 'FAQ-items',
                'ordering': ['page_key', 'order'],
            },
        ),
        migrations.CreateModel(
            name='KennisbankArtikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('categorie', models.CharField(blank=True, max_length=80, verbose_name='Categorie')),
                ('excerpt', models.TextField(blank=True, verbose_name='Samenvatting')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('active', models.BooleanField(default=True, verbose_name='Actief')),
            ],
            options={
                'verbose_name': 'Kennisbank-artikel',
                'verbose_name_plural': 'Kennisbank-artikelen',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KennisbankCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=120, verbose_name='Categorie')),
                ('aantal', models.CharField(blank=True, help_text="bijv. '214 artikelen'", max_length=40, verbose_name='Aantal (weergave)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
            ],
            options={
                'verbose_name': 'Kennisbank-categorie',
                'verbose_name_plural': 'Kennisbank-categorieën',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Technische sleutel (= URL-naam). Niet wijzigen.', max_length=60, unique=True, verbose_name='Pagina-sleutel')),
                ('label', models.CharField(max_length=120, verbose_name='Naam')),
                ('path', models.CharField(blank=True, help_text='Alleen ter info — wordt door de routing bepaald.', max_length=200, verbose_name='URL-pad')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO-titel')),
                ('seo_description', models.TextField(blank=True, max_length=320, verbose_name='SEO-omschrijving')),
                ('og_image', models.ImageField(blank=True, upload_to='og/', verbose_name='Deelafbeelding (OG)')),
                ('noindex', models.BooleanField(default=False, verbose_name='Uitsluiten van Google (noindex)')),
                ('eyebrow', models.CharField(blank=True, max_length=120, verbose_name='Bovenkop')),
                ('heading', models.CharField(blank=True, max_length=200, verbose_name='Titel (H1)')),
                ('intro', models.TextField(blank=True, verbose_name='Intro')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': "Pagina's",
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Naam')),
                ('role', models.CharField(max_length=160, verbose_name='Functie / voertuig')),
                ('quote', models.TextField(verbose_name='Review')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('active', models.BooleanField(default=True, verbose_name='Actief')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_score', models.CharField(default='9,1', max_length=10, verbose_name='Reviewscore')),
                ('review_count', models.CharField(default='2.840', max_length=20, verbose_name='Aantal reviews')),
                ('ondernemers_verzekerd', models.PositiveIntegerField(default=18742, verbose_name='Ondernemers verzekerd')),
                ('verzekeraars_label', models.CharField(default='12+', max_length=20, verbose_name='Verzekeraars (label)')),
                ('phone', models.CharField(default='088 - 123 45 67', max_length=40, verbose_name='Telefoon')),
                ('whatsapp', models.CharField(default='+31 6 12345678', max_length=40, verbose_name='WhatsApp-nummer')),
                ('email', models.EmailField(default='hallo@bestelautoverzekering.nl', max_length=254, verbose_name='E-mail')),
                ('afm_nummer', models.CharField(default='12345678', max_length=40, verbose_name='AFM-vergunning')),
                ('kvk_nummer', models.CharField(default='87654321', max_length=40, verbose_name='KvK-nummer')),
                ('footer_blurb', models.TextField(default='De verzekeringsspecialist voor ondernemers waarvan de bus het bedrijf is. Onafhankelijk, snel en zonder verzekeraarstaal.', verbose_name='Footer-tekst')),
            ],
            options={
                'verbose_name': 'Site-instellingen',
                'verbose_name_plural': 'Site-instellingen',
            },
        ),
        migrations.CreateModel(
            name='Situatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=120, verbose_name='Titel')),
                ('omschrijving', models.TextField(verbose_name='Omschrijving')),
                ('featured', models.BooleanField(default=False, verbose_name='Uitgelicht (grote kaart)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('active', models.BooleanField(default=True, verbose_name='Actief')),
            ],
            options={
                'verbose_name': 'Situatie',
                'verbose_name_plural': 'Situaties',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Verzekeraar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=120, verbose_name='Naam')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
                ('score', models.CharField(blank=True, max_length=10, verbose_name='Score')),
                ('premie_vanaf', models.CharField(blank=True, max_length=20, verbose_name='Premie vanaf (€)')),
                ('tags', models.CharField(blank=True, help_text='Komma-gescheiden.', max_length=255, verbose_name='Tags')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('active', models.BooleanField(default=True, verbose_name='Actief')),
            ],
            options={
                'verbose_name': 'Verzekeraar',
                'verbose_name_plural': 'Verzekeraars',
                'ordering': ['order', 'naam'],
            },
        ),
        migrations.CreateModel(
            name='DekkingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Kenmerk')),
                ('included', models.BooleanField(default=True, verbose_name='Inbegrepen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.dekkingstier')),
            ],
            options={
                'verbose_name': 'Dekkingskenmerk',
                'verbose_name_plural': 'Dekkingskenmerken',
                'ordering': ['order'],
            },
        ),
    ]
