# Generated by Django 5.1 on 2026-06-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kennisbankartikel',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Uitgelicht'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='gelezen',
            field=models.CharField(blank=True, help_text="bijv. '12.4k'", max_length=20, verbose_name='Aantal keer gelezen'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Afbeelding-URL'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='leestijd',
            field=models.CharField(blank=True, help_text="bijv. '4 min'", max_length=20, verbose_name='Leestijd'),
        ),
    ]
