# Generated by Django 5.1 on 2026-06-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_kennisbankartikel_featured_kennisbankartikel_gelezen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='situatie',
            name='badge',
            field=models.CharField(blank=True, help_text="bijv. 'POPULAIR'", max_length=30, verbose_name='Badge'),
        ),
        migrations.AddField(
            model_name='situatie',
            name='image_url',
            field=models.URLField(blank=True, help_text='Leeg = gestreepte placeholder.', verbose_name='Afbeelding-URL'),
        ),
    ]
