# Generated by Django 5.1 on 2026-06-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_situatie_badge_situatie_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='kennisbankcategorie',
            name='icon',
            field=models.CharField(choices=[('square', 'Vierkant (lijn)'), ('square-fill', 'Vierkant (vol)'), ('triangle', 'Driehoek'), ('pill', 'Pil'), ('diamond', 'Ruit'), ('bars', 'Strepen'), ('ring', 'Ring')], default='square', max_length=20, verbose_name='Icoon'),
        ),
    ]
