# Generated by Django 5.1 on 2026-06-16 14:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_kennisbankcategorie_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogartikel',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='kennisbankartikel',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='situatie',
            name='image_url',
        ),
        migrations.AddField(
            model_name='blogartikel',
            name='photo_alt',
            field=models.CharField(blank=True, help_text='Beschrijf de foto voor SEO en screenreaders.', max_length=300, verbose_name='Alt-tekst'),
        ),
        migrations.AddField(
            model_name='blogartikel',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fotocredit'),
        ),
        migrations.AddField(
            model_name='blogartikel',
            name='photo_local',
            field=models.CharField(blank=True, help_text='Wordt automatisch ingevuld door de Pexels-widget.', max_length=300, verbose_name='Foto lokaal pad'),
        ),
        migrations.AddField(
            model_name='blogartikel',
            name='photo_pexels_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pexels foto-ID'),
        ),
        migrations.AddField(
            model_name='blogartikel',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to=core.models._photo_upload_to, verbose_name='Foto uploaden'),
        ),
        migrations.AddField(
            model_name='blogartikel',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Foto URL (extern)'),
        ),
        migrations.AddField(
            model_name='expert',
            name='photo_alt',
            field=models.CharField(blank=True, help_text='Beschrijf de foto voor SEO en screenreaders.', max_length=300, verbose_name='Alt-tekst'),
        ),
        migrations.AddField(
            model_name='expert',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fotocredit'),
        ),
        migrations.AddField(
            model_name='expert',
            name='photo_local',
            field=models.CharField(blank=True, help_text='Wordt automatisch ingevuld door de Pexels-widget.', max_length=300, verbose_name='Foto lokaal pad'),
        ),
        migrations.AddField(
            model_name='expert',
            name='photo_pexels_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pexels foto-ID'),
        ),
        migrations.AddField(
            model_name='expert',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to=core.models._photo_upload_to, verbose_name='Foto uploaden'),
        ),
        migrations.AddField(
            model_name='expert',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Foto URL (extern)'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='photo_alt',
            field=models.CharField(blank=True, help_text='Beschrijf de foto voor SEO en screenreaders.', max_length=300, verbose_name='Alt-tekst'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fotocredit'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='photo_local',
            field=models.CharField(blank=True, help_text='Wordt automatisch ingevuld door de Pexels-widget.', max_length=300, verbose_name='Foto lokaal pad'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='photo_pexels_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pexels foto-ID'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to=core.models._photo_upload_to, verbose_name='Foto uploaden'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Foto URL (extern)'),
        ),
        migrations.AddField(
            model_name='review',
            name='photo_alt',
            field=models.CharField(blank=True, help_text='Beschrijf de foto voor SEO en screenreaders.', max_length=300, verbose_name='Alt-tekst'),
        ),
        migrations.AddField(
            model_name='review',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fotocredit'),
        ),
        migrations.AddField(
            model_name='review',
            name='photo_local',
            field=models.CharField(blank=True, help_text='Wordt automatisch ingevuld door de Pexels-widget.', max_length=300, verbose_name='Foto lokaal pad'),
        ),
        migrations.AddField(
            model_name='review',
            name='photo_pexels_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pexels foto-ID'),
        ),
        migrations.AddField(
            model_name='review',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to=core.models._photo_upload_to, verbose_name='Foto uploaden'),
        ),
        migrations.AddField(
            model_name='review',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Foto URL (extern)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_og_image',
            field=models.ImageField(blank=True, help_text='Gebruikt als een pagina zelf geen OG-afbeelding heeft.', null=True, upload_to='og/', verbose_name='Standaard deelafbeelding (OG)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pexels_api_key',
            field=models.CharField(blank=True, help_text='Gratis via pexels.com/api — heeft voorrang boven PEXELS_API_KEY in .env.', max_length=100, verbose_name='Pexels API-sleutel'),
        ),
        migrations.AddField(
            model_name='situatie',
            name='photo_alt',
            field=models.CharField(blank=True, help_text='Beschrijf de foto voor SEO en screenreaders.', max_length=300, verbose_name='Alt-tekst'),
        ),
        migrations.AddField(
            model_name='situatie',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fotocredit'),
        ),
        migrations.AddField(
            model_name='situatie',
            name='photo_local',
            field=models.CharField(blank=True, help_text='Wordt automatisch ingevuld door de Pexels-widget.', max_length=300, verbose_name='Foto lokaal pad'),
        ),
        migrations.AddField(
            model_name='situatie',
            name='photo_pexels_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pexels foto-ID'),
        ),
        migrations.AddField(
            model_name='situatie',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to=core.models._photo_upload_to, verbose_name='Foto uploaden'),
        ),
        migrations.AddField(
            model_name='situatie',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Foto URL (extern)'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='photo_alt',
            field=models.CharField(blank=True, help_text='Beschrijf de foto voor SEO en screenreaders.', max_length=300, verbose_name='Alt-tekst'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fotocredit'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='photo_local',
            field=models.CharField(blank=True, help_text='Wordt automatisch ingevuld door de Pexels-widget.', max_length=300, verbose_name='Foto lokaal pad'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='photo_pexels_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pexels foto-ID'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to=core.models._photo_upload_to, verbose_name='Foto uploaden'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Foto URL (extern)'),
        ),
    ]
