# Generated by Django 5.1 on 2026-06-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_blogartikel_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Pad zonder voor-/achter-slash, bv. verzekeraars/unive-bestelautoverzekering', max_length=255, unique=True, verbose_name='Slug (pad)')),
                ('contenttype', models.CharField(blank=True, max_length=40, verbose_name='Contenttype')),
                ('titel', models.CharField(max_length=300, verbose_name='Titel')),
                ('focus_keyword', models.CharField(blank=True, max_length=200, verbose_name='Focus-keyword')),
                ('zoekintentie', models.CharField(blank=True, max_length=40, verbose_name='Zoekintentie')),
                ('meta_title', models.CharField(blank=True, max_length=300, verbose_name='SEO-titel')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO-omschrijving')),
                ('image_url', models.URLField(blank=True, max_length=600, verbose_name='Afbeelding-URL')),
                ('image_alt', models.CharField(blank=True, max_length=400, verbose_name='Afbeelding alt')),
                ('image_credit', models.CharField(blank=True, max_length=300, verbose_name='Fotocredit')),
                ('image_credit_url', models.URLField(blank=True, max_length=600, verbose_name='Fotocredit-URL')),
                ('intro_html', models.TextField(blank=True, verbose_name='Intro (HTML)')),
                ('body_html', models.TextField(blank=True, verbose_name='Body (HTML)')),
                ('faq_html', models.TextField(blank=True, verbose_name='FAQ (HTML)')),
                ('conclusie_html', models.TextField(blank=True, verbose_name='Conclusie (HTML)')),
                ('cta_html', models.TextField(blank=True, verbose_name='CTA (HTML)')),
                ('interne_links_html', models.TextField(blank=True, verbose_name='Interne links (HTML)')),
                ('toc', models.JSONField(blank=True, default=list, verbose_name='Inhoudsopgave')),
                ('schema_jsonld', models.TextField(blank=True, verbose_name='Schema JSON-LD')),
                ('bronnen', models.TextField(blank=True, verbose_name='Bronnen')),
                ('gate_status', models.CharField(blank=True, max_length=20, verbose_name='Gate-status')),
                ('published', models.BooleanField(default=True, verbose_name='Gepubliceerd')),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content-pagina',
                'verbose_name_plural': "Content-pagina's",
                'ordering': ['contenttype', 'slug'],
                'indexes': [models.Index(fields=['contenttype'], name='core_conten_content_b45e32_idx')],
            },
        ),
    ]
