# Generated by Django 5.1 on 2026-06-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contentpagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='btw_nummer',
            field=models.CharField(default='NL820572937B01', max_length=40, verbose_name='BTW-nummer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kifid_nummer',
            field=models.CharField(default='300.008506', max_length=40, verbose_name='Kifid-aansluitnummer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_phone',
            field=models.BooleanField(default=False, help_text='Uit = nergens een telefoonnummer tonen.', verbose_name='Telefoonnummer tonen'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='afm_nummer',
            field=models.CharField(default='12012535', max_length=40, verbose_name='AFM-vergunning'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='kvk_nummer',
            field=models.CharField(default='34331885', max_length=40, verbose_name='KvK-nummer'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Telefoon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(default='+3197010252701', max_length=40, verbose_name='WhatsApp-nummer'),
        ),
    ]
