# Generated by Django 5.1 on 2026-06-17 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_btw_nummer_sitesettings_kifid_nummer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogartikel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.expert', verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='page',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.expert', verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='page',
            name='byline_date',
            field=models.CharField(blank=True, help_text="bijv. '12 juni 2026'", max_length=40, verbose_name='Datum (weergave)'),
        ),
        migrations.AddField(
            model_name='page',
            name='leestijd',
            field=models.CharField(blank=True, help_text="bijv. '5 min'", max_length=20, verbose_name='Leestijd'),
        ),
        migrations.AddField(
            model_name='page',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.expert', verbose_name='Gecontroleerd door'),
        ),
    ]
