# Generated by Django 5.1 on 2026-06-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogartikel_author_page_author_page_byline_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berekening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, verbose_name='Sessie-ID')),
                ('license_plate', models.CharField(blank=True, max_length=12, verbose_name='Kenteken')),
                ('is_van', models.BooleanField(default=False, verbose_name='Bestelauto (van)')),
                ('coverage', models.CharField(blank=True, max_length=4, verbose_name='Dekking')),
                ('vehicle_info', models.JSONField(blank=True, default=dict, verbose_name='Voertuiggegevens')),
                ('business_details', models.JSONField(blank=True, default=dict, verbose_name='Bedrijfsgegevens')),
                ('results', models.JSONField(blank=True, default=list, verbose_name='Premie-resultaten')),
                ('selected_result', models.JSONField(blank=True, default=dict, verbose_name='Gekozen verzekeraar')),
                ('additional_coverages', models.JSONField(blank=True, default=list, verbose_name='Aanvullende dekkingen')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='Aanvraaggegevens')),
                ('policy_number', models.CharField(blank=True, max_length=60, verbose_name='Polisnummer')),
                ('status', models.CharField(choices=[('started', 'Gestart'), ('vehicle-lookup', 'Kenteken opgezocht'), ('calculated', 'Premies berekend'), ('additional', 'Aanvullende dekkingen'), ('requested', 'Aangevraagd (polis)'), ('failed', 'Mislukt')], default='started', max_length=20, verbose_name='Status')),
                ('current_step', models.CharField(default='license-plate', max_length=30, verbose_name='Huidige stap')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Bijgewerkt')),
            ],
            options={
                'verbose_name': 'Berekening',
                'verbose_name_plural': 'Berekeningen',
                'ordering': ['-created_at'],
            },
        ),
    ]
