# Generated by Django 5.1 on 2026-06-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_berekening'),
    ]

    operations = [
        migrations.AddField(
            model_name='verzekeraar',
            name='aanschafwaarde',
            field=models.BooleanField(default=False, verbose_name='Aanschafwaarde-dekking'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='bijzonderheden',
            field=models.CharField(blank=True, max_length=120, verbose_name='Bijzonderheden'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='dagelijks_opzegbaar',
            field=models.BooleanField(default=False, verbose_name='Dagelijks opzegbaar'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='eenmalige_poliskosten',
            field=models.CharField(blank=True, help_text="bijv. '€ 0,00'", max_length=20, verbose_name='Eenmalige poliskosten'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='omschrijving',
            field=models.TextField(blank=True, help_text='Korte omschrijving van de verzekeraar.', verbose_name='Omschrijving'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='review_count',
            field=models.CharField(blank=True, help_text="bijv. '4.587'", max_length=20, verbose_name='Aantal reviews'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='score_contact',
            field=models.CharField(blank=True, max_length=5, verbose_name='Beoordeling · contact met verzekeraar'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='score_deskundigheid',
            field=models.CharField(blank=True, max_length=5, verbose_name='Beoordeling · deskundigheid'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='score_duidelijkheid',
            field=models.CharField(blank=True, max_length=5, verbose_name='Beoordeling · duidelijkheid'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='score_klantgerichtheid',
            field=models.CharField(blank=True, max_length=5, verbose_name='Beoordeling · klantgerichtheid'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='score_prijs_kwaliteit',
            field=models.CharField(blank=True, max_length=5, verbose_name='Beoordeling · prijs-kwaliteit'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='score_tevredenheid',
            field=models.CharField(blank=True, max_length=5, verbose_name='Beoordeling · algemene tevredenheid'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='score_vertrouwen',
            field=models.CharField(blank=True, max_length=5, verbose_name='Beoordeling · vertrouwen'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='telefonisch_contact',
            field=models.BooleanField(default=False, verbose_name='Telefonisch contact mogelijk'),
        ),
        migrations.AddField(
            model_name='verzekeraar',
            name='type_polis',
            field=models.CharField(blank=True, help_text="bijv. 'Digitale polis'", max_length=40, verbose_name='Type polis'),
        ),
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.CharField(blank=True, help_text='Alleen ter info, wordt door de routing bepaald.', max_length=200, verbose_name='URL-pad'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='pexels_api_key',
            field=models.CharField(blank=True, help_text='Gratis via pexels.com/api, heeft voorrang boven PEXELS_API_KEY in .env.', max_length=100, verbose_name='Pexels API-sleutel'),
        ),
        migrations.AlterField(
            model_name='verzekeraar',
            name='score',
            field=models.CharField(blank=True, help_text="Hoofdscore naast het logo, bijv. '9,0'.", max_length=10, verbose_name='Score (kop)'),
        ),
        migrations.AlterField(
            model_name='verzekeraar',
            name='tags',
            field=models.CharField(blank=True, help_text='Komma-gescheiden.', max_length=255, verbose_name='Kenmerken (tags)'),
        ),
    ]
