# Generated by Django 5.1 on 2026-06-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_verzekeraar_aanschafwaarde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kennisbankcategorie',
            name='link',
            field=models.CharField(blank=True, help_text="Waar de tegel naartoe gaat, bijv. '/beroep/' of '/verzekeraars/'. Leeg = naar de kennisbank.", max_length=200, verbose_name='Link (pad of URL)'),
        ),
    ]
