# Generated by Django 5.1 on 2026-06-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_kennisbankcategorie_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='situatie',
            name='link',
            field=models.CharField(blank=True, help_text="Waar de kaart naartoe gaat, bijv. '/beroep/'. Leeg = naar situaties & beroepen.", max_length=200, verbose_name='Link (pad of URL)'),
        ),
    ]
