# Generated by Django 5.1 on 2026-06-17 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_situatie_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(choices=[('nav', 'Hoofdmenu (bovenbalk)'), ('footer', 'Footer')], default='nav', max_length=10, verbose_name='Menu')),
                ('label', models.CharField(max_length=80, verbose_name='Label')),
                ('url', models.CharField(blank=True, help_text="bijv. '/dekkingen/'. Leeg = alleen kop (footer-kolom of dropdown-groep zonder eigen link).", max_length=200, verbose_name='Link (pad of URL)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('active', models.BooleanField(default=True, verbose_name='Actief')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem', verbose_name='Valt onder')),
            ],
            options={
                'verbose_name': 'Menu-item',
                'verbose_name_plural': "Menu's (nav + footer)",
                'ordering': ['menu', 'order', 'id'],
            },
        ),
    ]
