# Generated by Django 5.1 on 2026-06-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpagina',
            name='image_local',
            field=models.CharField(blank=True, help_text='Wordt gevuld door download_content_images; voert de {% picture %}-pipeline (WebP/JPEG).', max_length=300, verbose_name='Afbeelding lokaal pad'),
        ),
    ]
