# Generated by Django 5.1 on 2026-06-17 16:22

from django.db import migrations, models
from django.utils.text import slugify


def populate_expert_slugs(apps, schema_editor):
    """Give every existing expert a unique slug before the unique index lands."""
    Expert = apps.get_model('core', 'Expert')
    seen = set()
    for e in Expert.objects.all():
        base = slugify(e.name) or 'expert'
        slug, n = base, 2
        while slug in seen or Expert.objects.filter(slug=slug).exclude(pk=e.pk).exists():
            slug, n = f'{base}-{n}', n + 1
        e.slug = slug
        seen.add(slug)
        e.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contentpagina_image_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='sameas',
            field=models.TextField(blank=True, help_text='Eén URL per regel (LinkedIn enz.) voor de Person-entiteit / E-E-A-T.', verbose_name='Profielen (sameAs)'),
        ),
        migrations.AddField(
            model_name='expert',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Voor het Person-@id in de JSON-LD. Leeg = automatisch uit de naam.', max_length=140, verbose_name='Slug'),
        ),
        migrations.RunPython(populate_expert_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='expert',
            name='slug',
            field=models.SlugField(blank=True, help_text='Voor het Person-@id in de JSON-LD. Leeg = automatisch uit de naam.', max_length=140, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adres_plaats',
            field=models.CharField(blank=True, max_length=120, verbose_name='Vestiging · plaats'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adres_postcode',
            field=models.CharField(blank=True, max_length=16, verbose_name='Vestiging · postcode'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adres_straat',
            field=models.CharField(blank=True, max_length=160, verbose_name='Vestiging · straat + nr.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Gebruikt als Organization-logo in de JSON-LD (verplicht voor artikel-rich-results) en in het Google Knowledge Panel.', null=True, upload_to='brand/', verbose_name='Logo (vierkant, ≥112px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sameas',
            field=models.TextField(blank=True, help_text='Eén volledige URL per regel: LinkedIn, Facebook, X, Trustpilot… Verschijnen als sameAs in de Organization-graaf.', verbose_name='Social-profielen (sameAs)'),
        ),
    ]
