# Generated by Django 5.1 on 2026-06-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_expert_sameas_expert_slug_sitesettings_adres_plaats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustpilotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='autoverzekering.nl', max_length=120, verbose_name='Trustpilot-domein')),
                ('business_unit_id', models.CharField(blank=True, help_text='Door de API opgehaald o.b.v. het domein; wordt gecachet.', max_length=64, verbose_name='Business-unit-ID')),
                ('profile_url', models.URLField(default='https://nl.trustpilot.com/review/autoverzekering.nl', max_length=300, verbose_name='Profiel-URL')),
                ('trust_score', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='TrustScore (1–5)')),
                ('stars', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Sterren (1–5)')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Aantal reviews')),
                ('last_fetched', models.DateTimeField(blank=True, null=True, verbose_name='Laatst opgehaald')),
            ],
            options={
                'verbose_name': 'Trustpilot-profiel',
                'verbose_name_plural': 'Trustpilot-profiel',
            },
        ),
        migrations.CreateModel(
            name='TrustpilotReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True, verbose_name='Trustpilot-ID')),
                ('author', models.CharField(max_length=160, verbose_name='Auteur')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Sterren')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Titel')),
                ('text', models.TextField(blank=True, verbose_name='Tekst')),
                ('language', models.CharField(blank=True, max_length=8, verbose_name='Taal')),
                ('review_url', models.URLField(blank=True, max_length=400, verbose_name='Review-URL')),
                ('created_at', models.DateTimeField(verbose_name='Datum review')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='Opgehaald op')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Volgorde')),
            ],
            options={
                'verbose_name': 'Trustpilot-review',
                'verbose_name_plural': 'Trustpilot-reviews',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
