# Generated by Django 5.1 on 2026-06-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_trustpilotprofile_trustpilotreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='datum',
            field=models.CharField(blank=True, help_text="bijv. '4 juni 2026'", max_length=40, verbose_name='Datum (weergave)'),
        ),
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.CharField(blank=True, help_text="bijv. '10' of '9'", max_length=5, verbose_name='Cijfer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='role',
            field=models.CharField(help_text="Wordt onder de review getoond, bijv. 'Utrecht'.", max_length=160, verbose_name='Plaats / functie'),
        ),
    ]
