# Generated by Django 5.1 on 2026-06-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_review_datum_review_score_alter_review_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blok', models.CharField(choices=[('home_waarom', 'Home — Waarom-kaarten'), ('home_documenten', 'Home — Documenten'), ('home_trust', 'Home — Trust-cijfers (donkere balk)'), ('home_stappen', 'Home — In drie stappen'), ('home_info', 'Home — Meer over je motorverzekering (link-kolommen)'), ('home_contact_direct', 'Home — Contact: direct regelen'), ('home_contact_kanaal', 'Home — Contact: kanalen'), ('dekkingen_extra', 'Dekkingen — Aanvullende dekkingen'), ('dekkingen_matrix', 'Dekkingen — Dekkingsmatrix (rijen)'), ('dekkingen_eigenrisico', 'Dekkingen — Eigen-risico-opties'), ('over_ons_proces', 'Onze experts — Redactieproces'), ('over_ons_familie', 'Onze experts — Merkenfamilie'), ('klantenservice_weten', 'Klantenservice — Goed om te weten'), ('klantenservice_zelf', 'Klantenservice — Liever zelf regelen')], max_length=50, verbose_name='Blok')),
                ('volgorde', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('tag', models.CharField(blank=True, help_text="Klein mono-label of nummer, bv. 'EU', 'PDF', '01'.", max_length=40, verbose_name='Tag/label')),
                ('titel', models.CharField(blank=True, max_length=200, verbose_name='Titel')),
                ('tekst', models.TextField(blank=True, verbose_name='Tekst')),
                ('meta', models.CharField(blank=True, max_length=200, verbose_name='Subtekst / meta')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='Link (pad of URL)')),
                ('incl_wa', models.BooleanField(default=False, verbose_name='Inbegrepen bij WA')),
                ('incl_waplus', models.BooleanField(default=False, verbose_name='Inbegrepen bij WA + Casco')),
                ('incl_allrisk', models.BooleanField(default=False, verbose_name='Inbegrepen bij Allrisk')),
                ('actief', models.BooleanField(default=True, verbose_name='Actief')),
            ],
            options={
                'verbose_name': 'Kaart / lijst-item',
                'verbose_name_plural': 'Kaarten & lijst-items',
                'ordering': ['blok', 'volgorde'],
            },
        ),
        migrations.CreateModel(
            name='SectieTekst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(choices=[('home', 'Homepage'), ('dekkingen', 'Dekkingen'), ('over_ons', 'Onze experts'), ('klantenservice', 'Klantenservice'), ('blog', 'Blog'), ('blog_artikel', 'Blog-artikel'), ('kennisbank', 'Kennisbank'), ('kennisbank_artikel', 'Kennisbank-artikel'), ('premie_widget', 'Premie-widget (band)')], max_length=40, verbose_name='Pagina')),
                ('sleutel', models.SlugField(help_text="Technische naam binnen de pagina, bv. 'dekkingen', 'waarom', 'cta'.", max_length=60, verbose_name='Sectie-sleutel')),
                ('naam', models.CharField(blank=True, help_text='Alleen ter herkenning in de admin.', max_length=160, verbose_name='Omschrijving')),
                ('eyebrow', models.CharField(blank=True, max_length=120, verbose_name='Bovenkop (eyebrow)')),
                ('kop', models.CharField(blank=True, max_length=255, verbose_name='Kop')),
                ('tekst', models.TextField(blank=True, help_text="Mag meerdere alinea's bevatten (gescheiden door een lege regel).", verbose_name='Tekst')),
                ('cta_label', models.CharField(blank=True, max_length=120, verbose_name='Knop-tekst')),
                ('cta_url', models.CharField(blank=True, max_length=200, verbose_name='Knop-link (pad of URL)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
            ],
            options={
                'verbose_name': 'Sectietekst',
                'verbose_name_plural': 'Sectieteksten',
                'ordering': ['pagina', 'order', 'sleutel'],
                'unique_together': {('pagina', 'sleutel')},
            },
        ),
    ]
