# Generated by Django 5.1.15 on 2026-06-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_kaart_sectietekst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectietekst',
            name='pagina',
            field=models.CharField(choices=[('home', 'Homepage'), ('dekkingen', 'Dekkingen'), ('over_ons', 'Onze experts'), ('klantenservice', 'Klantenservice'), ('blog', 'Blog'), ('blog_artikel', 'Blog-artikel'), ('kennisbank', 'Kennisbank'), ('kennisbank_artikel', 'Kennisbank-artikel'), ('premie_widget', 'Premie-widget (band)'), ('premie_tool', 'Premie-tool (wizard-intro)')], max_length=40, verbose_name='Pagina'),
        ),
    ]
