# Generated by Django 5.1.15 on 2026-06-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_sectietekst_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='kennisbankartikel',
            name='body_html',
            field=models.TextField(blank=True, help_text='De volledige uitleg. Mag h2/p/ul/strong bevatten.', verbose_name='Artikel (HTML)'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='kort_antwoord',
            field=models.TextField(blank=True, help_text='Het directe antwoord in 1-3 zinnen (HTML toegestaan).', verbose_name='Kort antwoord'),
        ),
    ]
