# Generated by Django 5.1.15 on 2026-06-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_kennisbankartikel_body_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogartikel',
            name='body_html',
            field=models.TextField(blank=True, help_text='De volledige tekst. Mag h2/h3/p/ul/li/table/strong bevatten.', verbose_name='Artikel (HTML)'),
        ),
        migrations.AddField(
            model_name='blogartikel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Meta description (SEO)'),
        ),
        migrations.AddField(
            model_name='blogartikel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta title (SEO)'),
        ),
        migrations.AddField(
            model_name='blogartikel',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.expert', verbose_name='Gecontroleerd door'),
        ),
    ]
