# Generated by Django 5.1.15 on 2026-06-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_blogartikel_body_html_blogartikel_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='legal_naam',
            field=models.CharField(default='Finckers B.V.', help_text="Rechtspersoon achter de site (voor JSON-LD legalName en juridische pagina's).", max_length=160, verbose_name='Statutaire naam'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='adres_plaats',
            field=models.CharField(blank=True, default='Utrecht', max_length=120, verbose_name='Vestiging · plaats'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='adres_postcode',
            field=models.CharField(blank=True, default='3528 BJ', max_length=16, verbose_name='Vestiging · postcode'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='adres_straat',
            field=models.CharField(blank=True, default='Papendorpseweg 99', max_length=160, verbose_name='Vestiging · straat + nr.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='afm_nummer',
            field=models.CharField(default='12047091', max_length=40, verbose_name='AFM-vergunning'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='btw_nummer',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='BTW-nummer'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='kifid_nummer',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Kifid-aansluitnummer'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='kvk_nummer',
            field=models.CharField(default='76100200', max_length=40, verbose_name='KvK-nummer'),
        ),
    ]
