# Generated by Django 5.1.15 on 2026-06-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sitesettings_legal_naam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification',
            field=models.CharField(blank=True, default='', help_text='De content-waarde van de <meta name="google-site-verification">-tag (zonder de tag zelf). Leeg = geen tag.', max_length=100, verbose_name='Google Search Console verificatie'),
        ),
    ]
