# Generated by Django 5.1.15 on 2026-06-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sitesettings_google_site_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogartikel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Gebruikt als <lastmod> in de sitemap (verse-signaal).', verbose_name='Laatst bijgewerkt'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Gebruikt als <lastmod> in de sitemap (verse-signaal).', verbose_name='Laatst bijgewerkt'),
        ),
    ]
