# Generated by Django 5.1.15 on 2026-07-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_blogartikel_updated_at_kennisbankartikel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='aanvraag_notify_email',
            field=models.EmailField(blank=True, default='robin@rovabo.nl', help_text='Elke nieuwe polisaanvraag wordt naar dit adres gemaild. Leeg = geen notificatie.', max_length=254, verbose_name='Aanvraag-notificatie e-mail'),
        ),
    ]
